### ISSUE TITLE
关闭后蓝屏

### ISSUE THREAD

**Issue by qwerty6688** [1234567Yang/RtlSetProcessIsCritical-by-E#1]
调用之后关闭程序蓝屏，提示Critical_Process_Died，怎么解决

**Comment by 1234567Yang** [comment]
第二个还是第三个参数是逻辑型，设置是否为关键进程来着，把那个改成假，然后再加个判断是否成功。

如果成功再结束，不成功提示信息然后重试就好了。

**Comment by qwerty6688** [comment]
> 第二个还是第三个参数是逻辑型，设置是否为关键进程来着，把那个改成假，然后再加个判断是否成功。
> 
> 如果成功再结束，不成功提示信息然后重试就好了。

我去试试
